/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * ./test.h
 * 2023-10-16 15:23:06
 * Generated by rocket framework rocket_generator.py
 * Do not edit !!!
****************************************************/


#ifndef ./TEST_SERVICE_./TEST_H 
#define ./TEST_SERVICE_./TEST_H

#include <google/protobuf/service.h>
#include "./test/pb/./test.pb.h"

namespace ./test {

class testserviceImpl : public testservice {

 public:

  testserviceImpl() = default;

  ~testserviceImpl() = default;

  // override from testservice
  virtual void test(::google::protobuf::RpcController* controller,
                       const ::testreq* request,
                       ::testres* response,
                       ::google::protobuf::Closure* done);

  

};

}


#endif