/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * order_server.h
 * 2023-08-29 16:25:22
 * Generated by rocket framework rocket_generator.py
 * Do not edit !!!
****************************************************/


#ifndef ORDER_SERVER_SERVICE_ORDER_SERVER_H 
#define ORDER_SERVER_SERVICE_ORDER_SERVER_H

#include <google/protobuf/service.h>
#include "order_server/pb/order_server.pb.h"

namespace order_server {

class QueryServiceImpl : public QueryService {

 public:

  QueryServiceImpl() = default;

  ~QueryServiceImpl() = default;

  // override from QueryService//重写两个业务方法
  
  virtual void query_name(::google::protobuf::RpcController* controller,
                       const ::queryNameReq* request,
                       ::queryNameRes* response,
                       ::google::protobuf::Closure* done);

  // override from QueryService
  virtual void query_age(::google::protobuf::RpcController* controller,
                       const ::queryAgeReq* request,
                       ::queryAgeRes* response,
                       ::google::protobuf::Closure* done);

  

};

}


#endif